---
- hosts: "localhost"

# tasks:
#   # query a list of devices
#   - name: Obtain list of devices from Nautobot
#     debug:
#       msg: >
#         "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
#          manufactured by {{ item.value.device_type.manufacturer.name }}"
#     loop: "{{ query('networktocode.nautobot.lookup', 'devices',
#                     api_endpoint='http://localhost/',
#                     token='<redacted>') }}"
# # This example uses an API Filter
# tasks:
#   # query a list of devices
#   - name: Obtain list of devices from Nautobot
#     debug:
#       msg: >
#         "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
#          manufactured by {{ item.value.device_type.manufacturer.name }}"
#     loop: "{{ query('networktocode.nautobot.lookup', 'devices',
#                     api_endpoint='http://localhost/',
#                     api_filter='role=management tag=Dell'),
#                     token='<redacted>') }}"
# # Fetch bgp sessions for R1-device
# tasks:
#   - name: "Obtain bgp sessions for R1-Device"
#     debug:
#       msg: "{{ query('networktocode.nautobot.lookup', 'bgp_sessions',
#                      api_filter='device=R1-Device',
#                      api_endpoint='http://localhost/',
#                      token='<redacted>',
#                      plugin='mycustomstuff') }}"


  tasks:
    - name: Obtain list of devices from Nautobot
      set_fact:
        devices: "{{ query('networktocode.nautobot.lookup', 'devices', api_endpoint='http://10.41.41.10:8080/', api_filter='tag=avd', token='ff0fa3e62e02faa83c0dbd36a3395cc688c84051') }}"

    - name: Obtain list of interfaces from Nautobot
      set_fact:
        interfaces: "{{ query('networktocode.nautobot.lookup', 'interfaces', api_endpoint='http://10.41.41.10:8080/', token='ff0fa3e62e02faa83c0dbd36a3395cc688c84051') }}"

    - name: Obtain list of vlans from Nautobot
      set_fact:
        vlans: "{{ query('networktocode.nautobot.lookup', 'vlans', api_endpoint='http://10.41.41.10:8080/', api_filter='tag=avd', token='ff0fa3e62e02faa83c0dbd36a3395cc688c84051') }}"

    - name: Obtain list of vrfs from Nautobot
      set_fact:
        vrfs: "{{ query('networktocode.nautobot.lookup', 'vrfs', api_endpoint='http://10.41.41.10:8080/', api_filter='tag=avd', token='ff0fa3e62e02faa83c0dbd36a3395cc688c84051') }}"

    - name: Print devices fact
      debug:
        msg: "{{ vrfs }}"