---
- name: GraphQL Global Query (Run Once)
  hosts: nautobot
  connection: local
  gather_facts: false
  # vars:
  #   ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Get nautobot mlag pairs
      uri:
        url: "http://10.41.41.10:8080/api/graphql/"
        validate_certs: no
        method: POST
        headers:
          Authorization: 'Token ff0fa3e62e02faa83c0dbd36a3395cc688c84051'
        body_format: json
        body:
          query: '{{ lookup("template", "roles/nautobot-sync/templates/mlag_pairs.graphql") }}'
      register: nautobot_mlag_pairs_query
      run_once: true

    - name: Set Netbox Global Info Variable (Run Once)
      set_fact:
        nb_mlag_pairs: "{{ nautobot_mlag_pairs_query.json.data }}"
      run_once: true

    - name: debug
      debug:
        msg: "{{ nb_mlag_pairs }}"