---
- hosts: advania_nautobot
  connection: local
  gather_facts: false
  tasks:
    - name: Run nautobot-sync
      import_role:
        name: nautobot-sync
      # debugger: always

- hosts: advania_nautobot
  tasks:
    - name: Run avdbuilder
      import_role:
        name: avdbuilder
      vars:
        fabric_name: ADVANIA_FABRIC
        site_names: ["dja", "sat", "ste", "thu", "kro"]
      # debugger: always