---
- hosts: netbox
  connection: local
  gather_facts: false
  tasks:
    - name: Run netbox-sync
      import_role:
        name: netbox-sync
      # debugger: always

- hosts: netbox
  tasks:
    - name: Run avdbuilder
      import_role:
        name: avdbuilder
      vars:
        fabric_name: TEST-FABRIC
        site_names: ["dja", "sat"]
      # debugger: always

    - name: copy output to group_vars
      copy:
        src: "{{ item }}"
        dest: "group_vars/"
        mode: 0600
      with_fileglob:
        - "avdbuilder_vars/*"
      delegate_to: localhost