query {
  virtual_chassis_list(filters: {tag: ["avd"]}) {
    name
    members(filters: {status: "active", role: "l2leaf"}) {
      name
      status
      device_type {
        model
      }
      role {
        name
      }
      tags {
        name
      }
      rack {
        name
      }
      primary_ip4 {
        address
      }
      custom_field_data
      site {
        name
      }
      interfaces(filters: {tag: ["uplink"]}) {
        name
        cable {
          id
          a_terminations {
            ... on InterfaceType {
              name
              device {
                name
              }
            }
          }
          b_terminations {
            ... on InterfaceType {
              name
              device {
                name
              }
            }
          }
        }
      }
    }
  }
}
