avd_fabric_defaults:
  # copies any settings from here to top level fabric file.
  fabric_name: ADVANIA_FABRIC
  custom_structured_configuration_ntp:
    local_interface:
      name: Management1
      vrf: MGMT
    servers:
      - name: 0.se.pool.ntp.org
        preferred: false
        vrf: MGMT
      - name: 1.se.pool.ntp.org
        preferred: true
        vrf: MGMT
  evpn_rd_type:
    admin_subfield: overlay_loopback
  evpn_rt_type:
    admin_subfield: 65000
  bgp_maximum_paths: 4
  bgp_ecmp: 4
  evpn_ebgp_multihop: 10
  evpn_prevent_readvertise_to_server: true
  bfd_multihop:
    interval: 10000
    min_rx: 10000
    multiplier: 3
  vxlan_vlan_aware_bundles: false
  custom_structured_configuration_switchport_default:
    mode: routed

# Name must match site name in nautobot
dja:
  dc_defaults:
    mgmt_gateway: 172.17.192.1
  spine:
    defaults:
      loopback_ipv4_pool: 100.64.11.0/24
      bgp_as: '64513'
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
  l3leaf:
    defaults:
      virtual_router_mac_address: 00:1c:73:00:dc:00
      uplink_ipv4_pool: 100.64.10.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.64.11.0/24
      vtep_loopback_ipv4_pool: 100.64.12.0/24
      mlag_peer_l3_ipv4_pool: 100.64.13.0/24
      mlag_peer_ipv4_pool: 100.64.14.0/24
      # uplink_switches: [ dja-spine01, dja-spine02 ]
      max_uplink_switches: 4
      uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
      uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ Ethernet53/1, Ethernet54/1 ]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
    node_groups:
      dja-border:
        nodes:
          dja-border-01a:
            uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
          dja-border-01b:
            uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1]
      dja-leaf:
        nodes:
          dja-leaf-01a:
            uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1]
          dja-leaf-01b:
            uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1]

  l2leaf:
    defaults: false

  servers:

  # should match a site name + _defaults and copy any group vars to that DC file
  # not needed rn but should be grabbed

# Name must match site name in nautobot
sat:
  dc_defaults:
    mgmt_gateway: 172.17.192.1
  spine:
    defaults:
      loopback_ipv4_pool: 100.64.21.0/24
      bgp_as: '64515'
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
  l3leaf:
    defaults:
      virtual_router_mac_address: 00:1c:73:00:dc:00
      uplink_ipv4_pool: 100.64.20.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.64.21.0/24
      vtep_loopback_ipv4_pool: 100.64.22.0/24
      mlag_peer_l3_ipv4_pool: 100.64.23.0/24
      mlag_peer_ipv4_pool: 100.64.24.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
      uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ Ethernet53/1, Ethernet54/1 ]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
    node_groups:
      sat-border:
        nodes:
          sat-border-01a:
            uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
          sat-border-01b:
            uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1]
      sat-leaf:
        nodes:
          sat-leaf-01a:
            uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1]
          sat-leaf-01b:
            uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1]

  l2leaf:
    defaults: false
  # should match a site name + _defaults and copy any group vars to that DC file
  # not needed rn but should be grabbed