avd_fabric_defaults:
  # copies any settings from here to top level fabric file.
  fabric_name: ADVANIA_FABRIC
  # bgp peer groups passwords
  bgp_peer_groups:
    EVPN_OVERLAY_PEERS:
      password: $1c$U4tL2vQP9QwZlxIV1K3/pw==
    IPv4_UNDERLAY_PEERS:
      password: $1c$U4tL2vQP9QwZlxIV1K3/pw==
    MLAG_IPv4_UNDERLAY_PEER:
      password: $1c$U4tL2vQP9QwZlxIV1K3/pw==

  custom_structured_configuration_ntp:
    local_interface:
      name: Management1
      vrf: MGMT
    servers:
      - name: 0.se.pool.ntp.org
        preferred: false
        vrf: MGMT
      - name: 1.se.pool.ntp.org
        preferred: true
        vrf: MGMT
  evpn_rd_type:
    admin_subfield: overlay_loopback
  evpn_rt_type:
    admin_subfield: 65000
  bgp_maximum_paths: 4
  bgp_ecmp: 4
  evpn_ebgp_multihop: 10
  evpn_prevent_readvertise_to_server: true
  bfd_multihop:
    interval: 10000
    min_rx: 10000
    multiplier: 3
  vxlan_vlan_aware_bundles: false
  custom_structured_configuration_switchport_default:
    mode: routed
  l3_edge:
    p2p_links_ip_pools:
      borderleaf_dci_pool: 100.80.48.0/23
    p2p_links:
    # sat-border to thu-border
    - nodes: [ sat-border-01a, thu-border-01a ]
      id: 1
      interfaces: [ Ethernet54/1, Ethernet54/1 ]
      as: [ 64704, 64700 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
    # sat-border to thu-border
    - nodes: [ sat-border-01b, thu-border-01b ]
      id: 2
      interfaces: [ Ethernet54/1, Ethernet54/1 ]
      as: [ 64704, 64700 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
    # sat-border to kro-border
    - nodes: [ sat-border-01a, kro-border-01a ]
      id: 3
      interfaces: [ ethernet48, ethernet48 ]
      as: [ 64704, 64701 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
    # sat-border to ste-border
    - nodes: [ sat-border-01b, ste-border-01b ]
      id: 4
      interfaces: [ Ethernet53/1, Ethernet54/1 ]
      as: [ 64704, 64702 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
    # ste-border to thu-border
    - nodes: [ ste-border-01a, thu-border-01a ]
      id: 5
      interfaces: [ Ethernet54/1, Ethernet53/1 ]
      as: [ 64702, 64700 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
#    # thu-border to dja-border
    - nodes: [ thu-border-01b, dja-border-01a ]
      id: 6
      interfaces: [ ethernet48, ethernet48 ]
      as: [ 64700, 64703 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
#    # kro-border to dja-border
    - nodes: [ kro-border-01a, dja-border-01a ]
      id: 7
      interfaces: [ Ethernet53/1, Ethernet54/1 ]
      as: [ 64703, 64701 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true
#    # kro-border to dja-border
    - nodes: [ kro-border-01b, dja-border-01b ]
      id: 8
      interfaces: [ Ethernet53/1, Ethernet54/1 ]
      as: [ 64703, 64701 ]
      ip_pool: borderleaf_dci_pool
      bfd: true
      include_in_underlay_protocol: true

# Name must match site name in nautobot
dja:
  default_peering_devices: ["dja-border-01a", "dja-border-01b"]
  dc_defaults:
    mgmt_gateway: 10.255.117.1
    cvp_instance_ips:
      - 10.255.112.8
      - 10.255.112.24
      - 10.255.112.40
    cvp_ingestauth_key: 'yjgwg3m6q8DdnYX0hOTv'
    evpn_rd_type:
      admin_subfield: bgp_as
    name_servers:
      - 10.254.20.20
      - 10.254.20.20

    local_users:
      cvpadmin:
        privilege: 15
        role: network-admin
        sha512_password: "$6$QOlqKRqMkIiAXmn8$voT9NOqz4qKqRt1vn4WRYxexXY6T.K2jEKk3ZbVOEIesqyTp.MrrYUUhDFpjL8J2dH68LXJw6BeIq9IAj922h0"
      admin-nopassword:
        privilege: 15
        role: network-admin
        no_password: true

  spine:
    defaults:
      loopback_ipv4_pool: 100.80.11.0/24
      bgp_as: '64513'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
  l3leaf:
    defaults:
      virtual_router_mac_address: 00:1c:73:00:dc:00
      uplink_ipv4_pool: 100.80.10.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.80.11.0/24
      vtep_loopback_ipv4_pool: 100.80.12.0/24
      mlag_peer_l3_ipv4_pool: 100.80.13.0/24
      mlag_peer_ipv4_pool: 100.80.14.0/24
      # uplink_switches: [ dja-spine01, dja-spine02 ]
      max_uplink_switches: 4
      uplink_interfaces: [ethernet55/1, ethernet56/1]
      # uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ethernet55/1, ethernet56/1]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
    node_groups:
      dja-border:
        nodes:
          dja-border-01a:
            uplink_switch_interfaces: [Ethernet32/1, Ethernet32/1]
            uplink_switches: [dja-spine-01, dja-spine-02]
          dja-border-01b:
            uplink_switch_interfaces: [Ethernet31/1, Ethernet31/1]
            uplink_switches: [dja-spine-01, dja-spine-02]
      dja-leaf:
        nodes:
          dja-leaf-01a:
            uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
            uplink_switches: [dja-spine-01, dja-spine-02]
          dja-leaf-01b:
            uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1]
            uplink_switches: [dja-spine-01, dja-spine-02]

  l2leaf:
    defaults: false

# Name must match site name in nautobot
sat:
  dc_defaults:
    mgmt_gateway: 10.255.114.1
    cvp_instance_ips:
      - 10.255.112.8
      - 10.255.112.24
      - 10.255.112.40
    cvp_ingestauth_key: 'yjgwg3m6q8DdnYX0hOTv'
    evpn_rd_type:
      admin_subfield: bgp_as
    name_servers:
      - 10.254.20.20
      - 10.254.20.20

    local_users:
      cvpadmin:
        privilege: 15
        role: network-admin
        sha512_password: "$6$QOlqKRqMkIiAXmn8$voT9NOqz4qKqRt1vn4WRYxexXY6T.K2jEKk3ZbVOEIesqyTp.MrrYUUhDFpjL8J2dH68LXJw6BeIq9IAj922h0"
      admin-nopassword:
        privilege: 15
        role: network-admin
        no_password: true

  spine:
    defaults:
      loopback_ipv4_pool: 100.80.21.0/24
      bgp_as: '64515'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
  l3leaf:
    defaults:
      virtual_router_mac_address:  00:1c:73:00:dc:a1
      uplink_ipv4_pool: 100.80.20.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.80.21.0/24
      vtep_loopback_ipv4_pool: 100.80.22.0/24
      mlag_peer_l3_ipv4_pool: 100.80.23.0/24
      mlag_peer_ipv4_pool: 100.80.24.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ethernet49/1,ethernet50/1]
      # uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ethernet55/1, ethernet56/1]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
    node_groups:
      sat-border:
        nodes:
          sat-border-01a:
            uplink_switch_interfaces: [Ethernet32/1,Ethernet32/1]
            uplink_switches: [sat-spine-01, sat-spine-02]
          sat-border-01b:
            uplink_switch_interfaces: [Ethernet31/1,Ethernet31/1]
            uplink_switches: [sat-spine-01, sat-spine-02]
      sat-leaf:
        nodes:
          sat-leaf-01a:
            uplink_switch_interfaces: [Ethernet1/1,Ethernet1/1]
            uplink_switches: [sat-spine-01, sat-spine-02]
          sat-leaf-01b:
            uplink_switch_interfaces: [Ethernet2/1,Ethernet2/1]
            uplink_switches: [sat-spine-01, sat-spine-02]

  l2leaf:
    defaults: false
  # should match a site name + _defaults and copy any group vars to that DC file
  # not needed rn but should be grabbed

thu:
  dc_defaults:
    mgmt_gateway: 10.255.115.1
    cvp_instance_ips:
      - 10.255.112.8
      - 10.255.112.24
      - 10.255.112.40
    cvp_ingestauth_key: 'yjgwg3m6q8DdnYX0hOTv'
    evpn_rd_type:
      admin_subfield: bgp_as
    name_servers:
      - 10.254.20.20
      - 10.254.20.20

    local_users:
      cvpadmin:
        privilege: 15
        role: network-admin
        sha512_password: "$6$QOlqKRqMkIiAXmn8$voT9NOqz4qKqRt1vn4WRYxexXY6T.K2jEKk3ZbVOEIesqyTp.MrrYUUhDFpjL8J2dH68LXJw6BeIq9IAj922h0"
      admin-nopassword:
        privilege: 15
        role: network-admin
        no_password: true

  spine:
    defaults:
      loopback_ipv4_pool: 100.80.31.0/24
      bgp_as: '64512'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
  l3leaf:
    defaults:
      virtual_router_mac_address:  00:1c:73:00:dc:a1
      uplink_ipv4_pool: 100.80.30.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.80.31.0/24
      vtep_loopback_ipv4_pool: 100.80.32.0/24
      mlag_peer_l3_ipv4_pool: 100.80.33.0/24
      mlag_peer_ipv4_pool: 100.80.34.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ethernet49/1,ethernet50/1]
      # uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ethernet55/1, ethernet56/1]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
    node_groups:
      thu-border:
        nodes:
          thu-border-01a:
            uplink_switch_interfaces: [Ethernet32/1,Ethernet32/1]
            uplink_switches: [thu-spine-01, thu-spine-02]
          thu-border-01b:
            uplink_switch_interfaces: [Ethernet31/1,Ethernet31/1]
            uplink_switches: [thu-spine-01, thu-spine-02]
      thu-leaf:
        nodes:
          thu-leaf-01a:
            uplink_switch_interfaces: [Ethernet1/1,Ethernet1/1]
            uplink_switches: [thu-spine-01, thu-spine-02]
          thu-leaf-01b:
            uplink_switch_interfaces: [Ethernet2/1,Ethernet2/1]
            uplink_switches: [thu-spine-01, thu-spine-02]

  l2leaf:
    defaults: false


ste:
  dc_defaults:
    mgmt_gateway: 10.255.116.1
    cvp_instance_ips:
      - 10.255.112.8
      - 10.255.112.24
      - 10.255.112.40
    cvp_ingestauth_key: 'yjgwg3m6q8DdnYX0hOTv'
    evpn_rd_type:
      admin_subfield: bgp_as
    name_servers:
      - 10.254.20.20
      - 10.254.20.20

    local_users:
      cvpadmin:
        privilege: 15
        role: network-admin
        sha512_password: "$6$QOlqKRqMkIiAXmn8$voT9NOqz4qKqRt1vn4WRYxexXY6T.K2jEKk3ZbVOEIesqyTp.MrrYUUhDFpjL8J2dH68LXJw6BeIq9IAj922h0"
      admin-nopassword:
        privilege: 15
        role: network-admin
        no_password: true

  spine:
    defaults:
      loopback_ipv4_pool: 100.80.41.0/24
      bgp_as: '64514'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
  l3leaf:
    defaults:
      virtual_router_mac_address:  00:1c:73:00:dc:a1
      uplink_ipv4_pool: 100.80.40.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.80.41.0/24
      vtep_loopback_ipv4_pool: 100.80.42.0/24
      mlag_peer_l3_ipv4_pool: 100.80.43.0/24
      mlag_peer_ipv4_pool: 100.80.44.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ethernet49/1,ethernet50/1]
      # uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ethernet55/1, ethernet56/1]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
    node_groups:
      ste-border:
        nodes:
          ste-border-01a:
            uplink_switch_interfaces: [Ethernet32/1,Ethernet32/1]
            uplink_switches: [ste-spine-01, ste-spine-02]
          ste-border-01b:
            uplink_switch_interfaces: [Ethernet31/1,Ethernet31/1]
            uplink_switches: [ste-spine-01, ste-spine-02]
      ste-leaf:
        nodes:
          ste-leaf-01a:
            uplink_switch_interfaces: [Ethernet1/1,Ethernet1/1]
            uplink_switches: [ste-spine-01, ste-spine-02]
          ste-leaf-01b:
            uplink_switch_interfaces: [Ethernet2/1,Ethernet2/1]
            uplink_switches: [ste-spine-01, ste-spine-02]

  l2leaf:
    defaults: false

kro:
  dc_defaults:
    mgmt_gateway: 10.255.118.1
    cvp_instance_ips:
      - 10.255.112.8
      - 10.255.112.24
      - 10.255.112.40
    cvp_ingestauth_key: 'yjgwg3m6q8DdnYX0hOTv'
    evpn_rd_type:
      admin_subfield: bgp_as
    name_servers:
      - 10.254.20.20
      - 10.254.20.20

    local_users:
      cvpadmin:
        privilege: 15
        role: network-admin
        sha512_password: "$6$QOlqKRqMkIiAXmn8$voT9NOqz4qKqRt1vn4WRYxexXY6T.K2jEKk3ZbVOEIesqyTp.MrrYUUhDFpjL8J2dH68LXJw6BeIq9IAj922h0"
      admin-nopassword:
        privilege: 15
        role: network-admin
        no_password: true

  spine:
    defaults:
      loopback_ipv4_pool: 100.80.51.0/24
      bgp_as: '64515'
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
  l3leaf:
    defaults:
      virtual_router_mac_address:  00:1c:73:00:dc:a1
      uplink_ipv4_pool: 100.80.50.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.80.51.0/24
      vtep_loopback_ipv4_pool: 100.80.52.0/24
      mlag_peer_l3_ipv4_pool: 100.80.53.0/24
      mlag_peer_ipv4_pool: 100.80.54.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ethernet49/1,ethernet50/1]
      # uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ethernet55/1, ethernet56/1]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      structured_config:
        management_security:
          password:
            encryption_key_common: true
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
    node_groups:
      kro-border:
        nodes:
          kro-border-01a:
            uplink_switch_interfaces: [Ethernet32/1,Ethernet32/1]
            uplink_switches: [kro-spine-01, kro-spine-02]
          kro-border-01b:
            uplink_switch_interfaces: [Ethernet31/1,Ethernet31/1]
            uplink_switches: [kro-spine-01, kro-spine-02]
      kro-leaf:
        nodes:
          kro-leaf-01a:
            uplink_switch_interfaces: [Ethernet1/1,Ethernet1/1]
            uplink_switches: [kro-spine-01, kro-spine-02]
          kro-leaf-01b:
            uplink_switch_interfaces: [Ethernet2/1,Ethernet2/1]
            uplink_switches: [kro-spine-01, kro-spine-02]

  l2leaf:
    defaults: false