avd_fabric_defaults:
  fabric_local_as: 150
  # copies any settings from here to top level fabric file.
  fabric_name: ADVANIA_FABRIC
  custom_structured_configuration_ntp:
    local_interface:
      name: Management1
      vrf: MGMT
    servers:
      - name: 0.se.pool.ntp.org
        preferred: false
        vrf: MGMT
      - name: 1.se.pool.ntp.org
        preferred: true
        vrf: MGMT
  evpn_rd_type:
    admin_subfield: overlay_loopback
  evpn_rt_type:
    admin_subfield: 65000
  bgp_maximum_paths: 4
  bgp_ecmp: 4
  evpn_ebgp_multihop: 10
  evpn_prevent_readvertise_to_server: true
  bfd_multihop:
    interval: 10000
    min_rx: 10000
    multiplier: 3
  vxlan_vlan_aware_bundles: false
  custom_structured_configuration_switchport_default:
    mode: routed

# Name must match site name in nautobot
DC1:
  dc_defaults:
  spine:
    defaults:
      loopback_ipv4_pool: 100.64.11.0/24
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
  l3leaf:
    defaults:
      virtual_router_mac_address: 00:1c:73:00:dc:00
      uplink_ipv4_pool: 100.64.10.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.64.11.0/24
      vtep_loopback_ipv4_pool: 100.64.12.0/24
      mlag_peer_l3_ipv4_pool: 100.64.13.0/24
      mlag_peer_ipv4_pool: 100.64.14.0/24
      # uplink_switches: [ dc1-spine01, dc1-spine02 ]
      max_uplink_switches: 4
      uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
      uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ Ethernet53/1, Ethernet54/1 ]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
    node_groups:
      dc1-borderleaf1:
        nodes:
          dc1-borderleaf1a:
            uplink_switch_interfaces: [Ethernet5, Ethernet5]
          dc1-borderleaf1b:
            uplink_switch_interfaces: [Ethernet6, Ethernet6]
      dc1-leaf01:
        nodes:
          dc1-leaf01a:
            uplink_switch_interfaces: [Ethernet1, Ethernet1]
          dc1-leaf01b:
            uplink_switch_interfaces: [Ethernet2, Ethernet2]
      dc1-leaf2:
        nodes:
          dc1-leaf02a:
            uplink_switch_interfaces: [Ethernet3, Ethernet3]
          dc1-leaf02b:
            uplink_switch_interfaces: [Ethernet4, Ethernet4]

  l2leaf:
    defaults: false

  tenants:
    HEJEHJ:
      vrfs:
        NÅNTING:
          static_routes:
            - prefix: 1.1.3.0/24
              gw:
  servers:

  # should match a site name + _defaults and copy any group vars to that DC file
  # not needed rn but should be grabbed

# Name must match site name in nautobot
DC2:
  dc_defaults:
  spine:
    defaults:
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
  l3leaf:
    defaults:
      virtual_router_mac_address: 00:1c:73:00:dc:00
      uplink_ipv4_pool: 100.64.20.0/24
      loopback_ipv4_offset: 10
      loopback_ipv4_pool: 100.64.21.0/24
      vtep_loopback_ipv4_pool: 100.64.22.0/24
      mlag_peer_l3_ipv4_pool: 100.64.23.0/24
      mlag_peer_ipv4_pool: 100.64.24.0/24
      max_uplink_switches: 4
      uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
      uplink_interface_speed: forced 100gfull
      mlag_interfaces: [ Ethernet53/1, Ethernet54/1 ]
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp
      bgp_defaults:
        - 'no bgp default ipv4-unicast'
        - 'distance bgp 20 200 200'
        - 'graceful-restart restart-time 300'
        - 'graceful-restart'
        - 'bgp asn notation asdot'
      raw_eos_cli: |
        management security
          password encryption-key common
    node_groups:
      dc2-borderleaf1:
        nodes:
          dc2-borderleaf1a:
            uplink_switch_interfaces: [Ethernet5, Ethernet5]
          dc2-borderleaf1b:
            uplink_switch_interfaces: [Ethernet6, Ethernet6]
      dc2-leaf1:
        nodes:
          dc2-leaf01a:
            uplink_switch_interfaces: [Ethernet1, Ethernet1]
          dc2-leaf01b:
            uplink_switch_interfaces: [Ethernet2, Ethernet2]
      dc2-leaf2:
        nodes:
          dc2-leaf02a:
            uplink_switch_interfaces: [Ethernet3, Ethernet3]
          dc2-leaf02b:
            uplink_switch_interfaces: [Ethernet4, Ethernet4]

  l2leaf:
    defaults: false
  # should match a site name + _defaults and copy any group vars to that DC file
  # not needed rn but should be grabbed